Try to get more meaningful errors when E+ fails
On mac 10.14 instead of nothing, it'll show what is expected:
```
ep_testing.exceptions.EPTestingException: EnergyPlus failed!

stderr:

b'dyld: Symbol not found: __ZTINSt3__14__fs10filesystem16filesystem_errorE\n  Referenced from: /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmpzmjjoh08/ep_package/EnergyPlus-9.6.0-ed3a9d36c8-Darwin-macOS10.15-x86_64/libenergyplusapi.9.6.0.dylib (which was built for Mac OS X 10.15)\n  Expected in: /usr/lib/libc++.1.dylib\n in /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmpzmjjoh08/ep_package/EnergyPlus-9.6.0-ed3a9d36c8-Darwin-macOS10.15-x86_64/libenergyplusapi.9.6.0.dylib\n'

stdout:

b''
```